# We have edited this file at our own peril. We should consider refactoring these
# tasks so we don't fly in the face of the automatically generated warning below.
#
# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

unless ARGV.any? { |a| a =~ /^gems/ } # Don't load anything when running the gems:* tasks

  vendored_cucumber_bin = Dir["#{Rails.root}/vendor/{gems,plugins}/cucumber*/bin/cucumber"].first
  $LOAD_PATH.unshift(File.dirname(vendored_cucumber_bin) + '/../lib') unless vendored_cucumber_bin.nil?

  cucumber_opts = ENV['CI'] ? '--format progress -f rerun --out rerun.txt' : nil

  begin
    require 'cucumber/rake/task'

    namespace :cucumber do
      Cucumber::Rake::Task.new(:headless, 'Run all features that should pass in headless mode') do |t|
        t.binary = vendored_cucumber_bin # If nil, the gem's binary is used.
        t.fork = true # You may get faster startup if you set this to false
        t.profile = 'headless'
        t.cucumber_opts = cucumber_opts
      end

      Cucumber::Rake::Task.new(:browser, 'Run all features that should pass in a browser') do |t|
        t.binary = vendored_cucumber_bin
        t.fork = true # You may get faster startup if you set this to false
        t.profile = 'browser'
        t.cucumber_opts = cucumber_opts
      end

      Cucumber::Rake::Task.new(:headless_wip, 'Run features that are being worked on in headless mode') do |t|
        t.binary = vendored_cucumber_bin
        t.fork = true # You may get faster startup if you set this to false
        t.profile = 'headless_wip'
        t.cucumber_opts = cucumber_opts
      end

      Cucumber::Rake::Task.new(:browser_wip, 'Run features that are being worked on in browser mode') do |t|
        t.binary = vendored_cucumber_bin
        t.fork = true # You may get faster startup if you set this to false
        t.profile = 'browser_wip'
        t.cucumber_opts = cucumber_opts
      end

      Cucumber::Rake::Task.new(:rerun, 'Re-run previously failed scenarios') do |t|
        t.binary = vendored_cucumber_bin
        t.fork = true # You may get faster startup if you set this to false
        t.profile = 'rerun'
        t.cucumber_opts = '@rerun.txt --format progress'
      end

      Rake::Task['cucumber:browser'].enhance ['assets:precompile']

      desc 'Run all features in headless and browser modes'
      task :all => [:headless, :browser]
    end

    desc 'Alias for cucumber:headless and cucumber:browser'
    task :cucumber => 'cucumber:all'

  rescue LoadError
    desc 'cucumber rake task not available (cucumber not installed)'
    task :cucumber do
      abort 'Cucumber rake task is not available. Be sure to install cucumber as a gem or plugin'
    end
  end

end
