FROM rapidftr/rapidftr:latest

#Turn off Enquiries feature
ENV ENQUIRIES_FEATURE off

#Bundling RapidREG APK
ADD https://www.dropbox.com/sh/5prsudbaupcriga/AADLQ_MAW2iVspDRORYlUpyga/Android/RapidREG-dev.apk?dl=1 /rapidftr/public/RapidREG.apk

#Add default RapidREG logo
ADD logo.png /rapidftr/app/assets/images/new/logo.png